export const PROJECT_CONFIG = {
    approvalProgress:[
        {
            id:231,
            value:'待审批',
            word:'DSP'
        },
        {
            id:232,
            value:'已同意',
            word:'YTY'
        },
        {
            id:233,
            value:'已拒绝',
            word:'YJJ'
        },
        {
            id:234,
            value:'已撤销',
            word:'YCX'
        },
        {
            id:235,
            value:'已作废',
            word:'YZF'
        }
    ]
}
